# This file was generated by GoReleaser. DO NOT EDIT.
cask "ttcli" do
  version "0.4.1"

  on_macos do
    on_arm do
      sha256 "cbf4bfb7c150775c8fe5f9d68e91275fafcd462db0a9008e095d4443b4c8238e"
      url "https://github.com/j4y-w4lk3r/ttcli/releases/download/v#{version}/ttcli_#{version}_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "5c464087f0acfbf8c3cd49d93de3ff7128d5f1c78ac69516f5d8bb09f39adba3"
      url "https://github.com/j4y-w4lk3r/ttcli/releases/download/v#{version}/ttcli_#{version}_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "e58e8b18ceb0bd27c543f5746b8331c2533174c5cd4cfc9be0b01d6c15605e04"
      url "https://github.com/j4y-w4lk3r/ttcli/releases/download/v#{version}/ttcli_#{version}_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "1a585e1a031179ff6dee7a0d0f469f25a1da479c356a94f4a16055591038e165"
      url "https://github.com/j4y-w4lk3r/ttcli/releases/download/v#{version}/ttcli_#{version}_Linux_x86_64.tar.gz"
    end
  end

  name "ttcli"
  desc "TickTick from the terminal: tasks, lists, pomodoro/focus — headless session auth with auto-refresh."
  homepage "https://github.com/j4y-w4lk3r/ttcli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ttcli"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ttcli"]
    end
  end

  # No zap stanza required
end
