# This file was generated by GoReleaser. DO NOT EDIT.
cask "ttcli" do
  version "0.4.0"

  on_macos do
    on_arm do
      sha256 "e7c1ead186701ccc39dc8c66e2abbe0a335013c646f21f9d32b7d12d49f062f9"
      url "https://github.com/j4y-w4lk3r/ttcli/releases/download/v#{version}/ttcli_#{version}_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "db67c3439e7299afe17be5914a36e15c71c224cb8f1486f0358ebe8bdbb3134d"
      url "https://github.com/j4y-w4lk3r/ttcli/releases/download/v#{version}/ttcli_#{version}_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "3ad7ca7f30dfb65d65d920c2bd7851667347a4b7dcd5bc1ada2f00e62bd37dda"
      url "https://github.com/j4y-w4lk3r/ttcli/releases/download/v#{version}/ttcli_#{version}_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "4c5838c2a2572e89c3c392008bd86941452359c3894e8db2d0e0101ebf41809d"
      url "https://github.com/j4y-w4lk3r/ttcli/releases/download/v#{version}/ttcli_#{version}_Linux_x86_64.tar.gz"
    end
  end

  name "ttcli"
  desc "TickTick from the terminal: tasks, lists, pomodoro/focus — headless session auth with auto-refresh."
  homepage "https://github.com/j4y-w4lk3r/ttcli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ttcli"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ttcli"]
    end
  end

  # No zap stanza required
end
