# This file was generated by GoReleaser. DO NOT EDIT.
cask "ttcli" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "963b145e571bdf194ba4b9e876c601a79630f14d3936ba56942b223fde5961a5"
      url "https://github.com/j4y-w4lk3r/ttcli/releases/download/v#{version}/ttcli_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "a92c7036c864e2ae204de20f418f84a55d37ddd66402354db476716ed828307c"
      url "https://github.com/j4y-w4lk3r/ttcli/releases/download/v#{version}/ttcli_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "fffcd82716bb2879a91482822c0baa7fed4c4cc62956e22b80fc216fd097e965"
      url "https://github.com/j4y-w4lk3r/ttcli/releases/download/v#{version}/ttcli_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "77ce8aa62895de1913d87c32b57264e0994403490b14b44bacc2bd5873876f2b"
      url "https://github.com/j4y-w4lk3r/ttcli/releases/download/v#{version}/ttcli_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "ttcli"
  desc "TickTick from the terminal: tasks, lists, pomodoro/focus — headless session auth with auto-refresh."
  homepage "https://github.com/j4y-w4lk3r/ttcli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ttcli"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ttcli"]
    end
  end

  # No zap stanza required

end
